AllCops:
  Exclude:
    - 'gloo.gemspec'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Naming/PredicateName:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Security/Eval:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Metrics/MethodLength:
  # Default is 10. I'm starting high and will work down.
  Max: 17
  Enabled: true
Metrics/CyclomaticComplexity:
  # Default is 6
  Max: 9
Naming/MethodParameterName:
  # Default value is 3
  MinNameLength: 2

# Might want to try re-enabling these:
Metrics/AbcSize:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Lint/NonDeterministicRequireOrder:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
