AllCops:
  Exclude:
    - 'gloo.gemspec'

# -------------- Layout -------------- #
Layout/SpaceInsideParens:
  EnforcedStyle: space
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
Layout/SpaceInsideReferenceBrackets:
  Enabled: true
  EnforcedStyle: space

# -------------- Style -------------- #
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantReturn:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false

# -------------- Naming -------------- #
Naming/PredicateName:
  Enabled: true
Naming/AccessorMethodName:
  Enabled: false

# -------------- Metrics -------------- #
Metrics/MethodLength:
  Max: 17   # Default is 10
  Enabled: true
Metrics/CyclomaticComplexity:
  Max: 9   # Default is 6
Naming/MethodParameterName:
  MinNameLength: 2   # Default value is 3
Metrics/PerceivedComplexity:
  Max: 10   # default value is 7
Metrics/ClassLength:
  Max: 157   # default is 100
Metrics/AbcSize:
  Max: 37   # default is 15

# -------------- Lint -------------- #
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/NonDeterministicRequireOrder:
  Enabled: false

# -------------- Security -------------- #
Security/Eval:
  Enabled: true
