Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantSelf:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

# Might want to try re-enabling these:
Metrics/AbcSize:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Lint/NonDeterministicRequireOrder:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
